/** REAL measured part bounds of the 10 Tripo creature GLBs (world-space AABB
 *  per mesh node). Generated by tools/inspect-glb.mjs --fixtures — do not
 *  hand-edit; re-run the tool if an asset is regenerated. */
export interface FixturePart {
  name: string;
  center: [number, number, number];
  size: [number, number, number];
  tris: number;
}

export const CREATURE_PART_FIXTURES: Record<string, FixturePart[]> = {
  "feeder_cricket": [
    {
      "name": "tripo_part_0",
      "center": [
        0,
        0.106,
        -0.07
      ],
      "size": [
        0.184,
        0.211,
        0.448
      ],
      "tris": 7776
    },
    {
      "name": "tripo_part_1",
      "center": [
        0.115,
        0.136,
        -0.212
      ],
      "size": [
        0.1,
        0.263,
        0.395
      ],
      "tris": 3408
    },
    {
      "name": "tripo_part_2",
      "center": [
        0.001,
        0.102,
        0.3
      ],
      "size": [
        0.497,
        0.2,
        0.374
      ],
      "tris": 2683
    },
    {
      "name": "tripo_part_3",
      "center": [
        0.17,
        0.079,
        0.045
      ],
      "size": [
        0.306,
        0.121,
        0.049
      ],
      "tris": 986
    },
    {
      "name": "tripo_part_4",
      "center": [
        -0.171,
        0.08,
        0.039
      ],
      "size": [
        0.305,
        0.123,
        0.06
      ],
      "tris": 994
    },
    {
      "name": "tripo_part_5",
      "center": [
        -0.07,
        0.073,
        -0.386
      ],
      "size": [
        0.091,
        0.022,
        0.208
      ],
      "tris": 305
    },
    {
      "name": "tripo_part_6",
      "center": [
        -0.118,
        0.135,
        -0.213
      ],
      "size": [
        0.096,
        0.267,
        0.401
      ],
      "tris": 3328
    },
    {
      "name": "tripo_part_7",
      "center": [
        -0.117,
        0.089,
        0.159
      ],
      "size": [
        0.176,
        0.112,
        0.141
      ],
      "tris": 758
    },
    {
      "name": "tripo_part_8",
      "center": [
        0.115,
        0.087,
        0.16
      ],
      "size": [
        0.172,
        0.107,
        0.143
      ],
      "tris": 696
    },
    {
      "name": "tripo_part_9",
      "center": [
        0.071,
        0.073,
        -0.386
      ],
      "size": [
        0.089,
        0.022,
        0.205
      ],
      "tris": 224
    }
  ],
  "cherry_shrimp": [
    {
      "name": "tripo_part_0",
      "center": [
        0.002,
        0.293,
        0.25
      ],
      "size": [
        0.244,
        0.298,
        0.478
      ],
      "tris": 7537
    },
    {
      "name": "tripo_part_1",
      "center": [
        0.006,
        0.224,
        -0.127
      ],
      "size": [
        0.19,
        0.194,
        0.324
      ],
      "tris": 5558
    },
    {
      "name": "tripo_part_10",
      "center": [
        -0.054,
        0.125,
        0.211
      ],
      "size": [
        0.093,
        0.112,
        0.138
      ],
      "tris": 392
    },
    {
      "name": "tripo_part_11",
      "center": [
        -0.093,
        0.105,
        -0.01
      ],
      "size": [
        0.169,
        0.113,
        0.117
      ],
      "tris": 526
    },
    {
      "name": "tripo_part_12",
      "center": [
        -0.116,
        0.104,
        0.083
      ],
      "size": [
        0.212,
        0.101,
        0.056
      ],
      "tris": 356
    },
    {
      "name": "tripo_part_13",
      "center": [
        0.094,
        0.103,
        -0.026
      ],
      "size": [
        0.143,
        0.115,
        0.153
      ],
      "tris": 316
    },
    {
      "name": "tripo_part_2",
      "center": [
        -0.105,
        0.08,
        0.161
      ],
      "size": [
        0.197,
        0.145,
        0.153
      ],
      "tris": 951
    },
    {
      "name": "tripo_part_3",
      "center": [
        0.007,
        0.2,
        -0.376
      ],
      "size": [
        0.257,
        0.148,
        0.226
      ],
      "tris": 3922
    },
    {
      "name": "tripo_part_4",
      "center": [
        0.046,
        0.12,
        0.233
      ],
      "size": [
        0.061,
        0.112,
        0.136
      ],
      "tris": 566
    },
    {
      "name": "tripo_part_5",
      "center": [
        0.114,
        0.078,
        0.047
      ],
      "size": [
        0.181,
        0.157,
        0.056
      ],
      "tris": 504
    },
    {
      "name": "tripo_part_6",
      "center": [
        -0.025,
        0.118,
        0.242
      ],
      "size": [
        0.041,
        0.115,
        0.152
      ],
      "tris": 473
    },
    {
      "name": "tripo_part_7",
      "center": [
        0.122,
        0.078,
        0.118
      ],
      "size": [
        0.199,
        0.147,
        0.073
      ],
      "tris": 408
    },
    {
      "name": "tripo_part_8",
      "center": [
        0.101,
        0.094,
        0.185
      ],
      "size": [
        0.164,
        0.116,
        0.142
      ],
      "tris": 376
    },
    {
      "name": "tripo_part_9",
      "center": [
        0.064,
        0.147,
        0.196
      ],
      "size": [
        0.095,
        0.077,
        0.119
      ],
      "tris": 292
    }
  ],
  "nerite_snail": [
    {
      "name": "tripo_part_0",
      "center": [
        -0.057,
        0.367,
        -0.002
      ],
      "size": [
        0.836,
        0.51,
        0.614
      ],
      "tris": 5437
    },
    {
      "name": "tripo_part_1",
      "center": [
        -0.11,
        0.096,
        0
      ],
      "size": [
        0.758,
        0.193,
        0.651
      ],
      "tris": 4662
    },
    {
      "name": "tripo_part_2",
      "center": [
        0.302,
        0.126,
        0.023
      ],
      "size": [
        0.376,
        0.221,
        0.541
      ],
      "tris": 1510
    },
    {
      "name": "tripo_part_3",
      "center": [
        -0.03,
        0.559,
        0.168
      ],
      "size": [
        0.164,
        0.054,
        0.079
      ],
      "tris": 81
    },
    {
      "name": "tripo_part_4",
      "center": [
        -0.15,
        0.57,
        -0.128
      ],
      "size": [
        0.128,
        0.047,
        0.039
      ],
      "tris": 24
    }
  ],
  "neon_tetra": [
    {
      "name": "tripo_part_0",
      "center": [
        0,
        0.189,
        0.01
      ],
      "size": [
        0.158,
        0.2,
        0.658
      ],
      "tris": 3451
    },
    {
      "name": "tripo_part_1",
      "center": [
        0,
        0.186,
        -0.386
      ],
      "size": [
        0.049,
        0.328,
        0.206
      ],
      "tris": 1453
    },
    {
      "name": "tripo_part_10",
      "center": [
        -0.001,
        0.275,
        -0.229
      ],
      "size": [
        0.035,
        0.038,
        0.075
      ],
      "tris": 122
    },
    {
      "name": "tripo_part_11",
      "center": [
        -0.079,
        0.221,
        0.39
      ],
      "size": [
        0.008,
        0.037,
        0.036
      ],
      "tris": 40
    },
    {
      "name": "tripo_part_12",
      "center": [
        0.08,
        0.222,
        0.39
      ],
      "size": [
        0.008,
        0.036,
        0.036
      ],
      "tris": 21
    },
    {
      "name": "tripo_part_2",
      "center": [
        0,
        0.208,
        0.393
      ],
      "size": [
        0.161,
        0.189,
        0.193
      ],
      "tris": 2241
    },
    {
      "name": "tripo_part_3",
      "center": [
        -0.002,
        0.303,
        0.078
      ],
      "size": [
        0.141,
        0.08,
        0.563
      ],
      "tris": 1213
    },
    {
      "name": "tripo_part_4",
      "center": [
        0.003,
        0.372,
        0.014
      ],
      "size": [
        0.045,
        0.113,
        0.182
      ],
      "tris": 787
    },
    {
      "name": "tripo_part_5",
      "center": [
        -0.002,
        0.089,
        -0.12
      ],
      "size": [
        0.045,
        0.177,
        0.225
      ],
      "tris": 777
    },
    {
      "name": "tripo_part_6",
      "center": [
        -0.018,
        0.06,
        0.053
      ],
      "size": [
        0.028,
        0.084,
        0.11
      ],
      "tris": 550
    },
    {
      "name": "tripo_part_7",
      "center": [
        0.019,
        0.061,
        0.055
      ],
      "size": [
        0.028,
        0.086,
        0.114
      ],
      "tris": 518
    },
    {
      "name": "tripo_part_8",
      "center": [
        -0.064,
        0.115,
        0.245
      ],
      "size": [
        0.027,
        0.063,
        0.128
      ],
      "tris": 361
    },
    {
      "name": "tripo_part_9",
      "center": [
        0.065,
        0.115,
        0.243
      ],
      "size": [
        0.027,
        0.064,
        0.123
      ],
      "tris": 268
    }
  ],
  "guppy": [
    {
      "name": "tripo_part_0",
      "center": [
        0,
        0.357,
        0.254
      ],
      "size": [
        0.057,
        0.714,
        0.47
      ],
      "tris": 8494
    },
    {
      "name": "tripo_part_1",
      "center": [
        0,
        0.36,
        -0.197
      ],
      "size": [
        0.187,
        0.296,
        0.581
      ],
      "tris": 8734
    },
    {
      "name": "tripo_part_2",
      "center": [
        0,
        0.613,
        -0.015
      ],
      "size": [
        0.044,
        0.279,
        0.307
      ],
      "tris": 2458
    }
  ],
  "zebra_danio": [
    {
      "name": "tripo_part_0",
      "center": [
        0,
        0.177,
        0.088
      ],
      "size": [
        0.146,
        0.214,
        0.802
      ],
      "tris": 9638
    },
    {
      "name": "tripo_part_1",
      "center": [
        0.002,
        0.155,
        -0.377
      ],
      "size": [
        0.038,
        0.256,
        0.224
      ],
      "tris": 2336
    },
    {
      "name": "tripo_part_2",
      "center": [
        -0.076,
        0.094,
        0.218
      ],
      "size": [
        0.063,
        0.098,
        0.148
      ],
      "tris": 1458
    },
    {
      "name": "tripo_part_3",
      "center": [
        0.076,
        0.094,
        0.218
      ],
      "size": [
        0.063,
        0.096,
        0.149
      ],
      "tris": 1243
    },
    {
      "name": "tripo_part_4",
      "center": [
        0,
        0.289,
        -0.096
      ],
      "size": [
        0.033,
        0.105,
        0.185
      ],
      "tris": 2122
    },
    {
      "name": "tripo_part_5",
      "center": [
        0,
        0.062,
        -0.125
      ],
      "size": [
        0.03,
        0.123,
        0.194
      ],
      "tris": 1462
    },
    {
      "name": "tripo_part_6",
      "center": [
        0.024,
        0.052,
        0.05
      ],
      "size": [
        0.024,
        0.048,
        0.095
      ],
      "tris": 640
    },
    {
      "name": "tripo_part_7",
      "center": [
        -0.025,
        0.053,
        0.047
      ],
      "size": [
        0.024,
        0.048,
        0.087
      ],
      "tris": 310
    }
  ],
  "otocinclus": [
    {
      "name": "tripo_part_0",
      "center": [
        0,
        0.171,
        0.086
      ],
      "size": [
        0.172,
        0.199,
        0.807
      ],
      "tris": 10635
    },
    {
      "name": "tripo_part_1",
      "center": [
        0.077,
        0.104,
        0.205
      ],
      "size": [
        0.039,
        0.066,
        0.135
      ],
      "tris": 2262
    },
    {
      "name": "tripo_part_2",
      "center": [
        0,
        0.295,
        0.059
      ],
      "size": [
        0.038,
        0.148,
        0.184
      ],
      "tris": 2599
    },
    {
      "name": "tripo_part_3",
      "center": [
        0,
        0.155,
        -0.373
      ],
      "size": [
        0.028,
        0.229,
        0.23
      ],
      "tris": 2559
    },
    {
      "name": "tripo_part_4",
      "center": [
        0.034,
        0.051,
        0.096
      ],
      "size": [
        0.047,
        0.102,
        0.117
      ],
      "tris": 1737
    },
    {
      "name": "tripo_part_5",
      "center": [
        -0.034,
        0.053,
        0.091
      ],
      "size": [
        0.046,
        0.105,
        0.109
      ],
      "tris": 1354
    },
    {
      "name": "tripo_part_6",
      "center": [
        -0.077,
        0.104,
        0.206
      ],
      "size": [
        0.04,
        0.066,
        0.136
      ],
      "tris": 1268
    },
    {
      "name": "tripo_part_7",
      "center": [
        0,
        0.076,
        -0.057
      ],
      "size": [
        0.027,
        0.084,
        0.127
      ],
      "tris": 1255
    }
  ],
  "mystery_snail": [
    {
      "name": "tripo_part_0",
      "center": [
        -0.037,
        0.146,
        -0.002
      ],
      "size": [
        0.886,
        0.292,
        0.742
      ],
      "tris": 11599
    },
    {
      "name": "tripo_part_1",
      "center": [
        -0.057,
        0.35,
        -0.001
      ],
      "size": [
        0.864,
        0.624,
        0.752
      ],
      "tris": 9452
    },
    {
      "name": "tripo_part_2",
      "center": [
        0.342,
        0.266,
        0
      ],
      "size": [
        0.288,
        0.477,
        0.717
      ],
      "tris": 2346
    }
  ],
  "daphnia": [
    {
      "name": "tripo_part_0",
      "center": [
        0,
        0.457,
        -0.164
      ],
      "size": [
        0.328,
        0.914,
        0.653
      ],
      "tris": 7738
    },
    {
      "name": "tripo_part_1",
      "center": [
        0.14,
        0.762,
        0.279
      ],
      "size": [
        0.261,
        0.346,
        0.404
      ],
      "tris": 601
    },
    {
      "name": "tripo_part_10",
      "center": [
        -0.02,
        0.708,
        0.045
      ],
      "size": [
        0.022,
        0.032,
        0.06
      ],
      "tris": 26
    },
    {
      "name": "tripo_part_11",
      "center": [
        0.25,
        0.644,
        0.335
      ],
      "size": [
        0.03,
        0.082,
        0.024
      ],
      "tris": 1
    },
    {
      "name": "tripo_part_2",
      "center": [
        -0.091,
        0.523,
        -0.155
      ],
      "size": [
        0.141,
        0.694,
        0.213
      ],
      "tris": 585
    },
    {
      "name": "tripo_part_3",
      "center": [
        -0.023,
        0.777,
        0.024
      ],
      "size": [
        0.144,
        0.192,
        0.205
      ],
      "tris": 380
    },
    {
      "name": "tripo_part_4",
      "center": [
        0.046,
        0.779,
        0.024
      ],
      "size": [
        0.097,
        0.196,
        0.203
      ],
      "tris": 374
    },
    {
      "name": "tripo_part_5",
      "center": [
        -0.099,
        0.503,
        -0.316
      ],
      "size": [
        0.081,
        0.354,
        0.198
      ],
      "tris": 544
    },
    {
      "name": "tripo_part_6",
      "center": [
        0.101,
        0.503,
        -0.314
      ],
      "size": [
        0.078,
        0.353,
        0.194
      ],
      "tris": 536
    },
    {
      "name": "tripo_part_7",
      "center": [
        -0.14,
        0.762,
        0.279
      ],
      "size": [
        0.265,
        0.348,
        0.399
      ],
      "tris": 511
    },
    {
      "name": "tripo_part_8",
      "center": [
        0.092,
        0.523,
        -0.155
      ],
      "size": [
        0.141,
        0.697,
        0.209
      ],
      "tris": 479
    },
    {
      "name": "tripo_part_9",
      "center": [
        0.02,
        0.709,
        0.044
      ],
      "size": [
        0.023,
        0.033,
        0.061
      ],
      "tris": 37
    }
  ],
  "isopod": [
    {
      "name": "tripo_part_0",
      "center": [
        0,
        0.185,
        -0.057
      ],
      "size": [
        0.349,
        0.282,
        0.761
      ],
      "tris": 11137
    },
    {
      "name": "tripo_part_1",
      "center": [
        0,
        0.084,
        -0.065
      ],
      "size": [
        0.46,
        0.168,
        0.855
      ],
      "tris": 7110
    },
    {
      "name": "tripo_part_2",
      "center": [
        0.001,
        0.192,
        0.324
      ],
      "size": [
        0.175,
        0.16,
        0.105
      ],
      "tris": 1789
    },
    {
      "name": "tripo_part_3",
      "center": [
        -0.137,
        0.101,
        0.406
      ],
      "size": [
        0.254,
        0.107,
        0.164
      ],
      "tris": 326
    },
    {
      "name": "tripo_part_4",
      "center": [
        0.084,
        0.149,
        0.068
      ],
      "size": [
        0.091,
        0.112,
        0.531
      ],
      "tris": 5343
    },
    {
      "name": "tripo_part_5",
      "center": [
        0.058,
        0.057,
        -0.434
      ],
      "size": [
        0.027,
        0.051,
        0.098
      ],
      "tris": 180
    },
    {
      "name": "tripo_part_6",
      "center": [
        0.133,
        0.104,
        0.398
      ],
      "size": [
        0.246,
        0.1,
        0.174
      ],
      "tris": 312
    },
    {
      "name": "tripo_part_7",
      "center": [
        -0.085,
        0.149,
        0.062
      ],
      "size": [
        0.102,
        0.105,
        0.529
      ],
      "tris": 3312
    }
  ],
};

