/**
 * inspect-glb.mjs — compact structural report for one or more GLB files.
 * Prints per file: scene node tree (with mesh part names), triangle/vertex
 * counts, materials (PBR params + texture sizes), animations and bbox size.
 *
 * Usage: node tools/inspect-glb.mjs <file.glb> [more.glb ...]
 * No network, no paid APIs — pure local inspection via @gltf-transform/core.
 */
import path from "node:path";
import { NodeIO } from "@gltf-transform/core";
import { KHRONOS_EXTENSIONS } from "@gltf-transform/extensions";
import { inspect } from "@gltf-transform/functions";

const io = new NodeIO().registerExtensions(KHRONOS_EXTENSIONS);

/** Transform a local-space AABB through a 4x4 (column-major) world matrix. */
function transformBounds(min, max, m) {
  const outMin = [Infinity, Infinity, Infinity];
  const outMax = [-Infinity, -Infinity, -Infinity];
  for (let i = 0; i < 8; i++) {
    const p = [i & 1 ? max[0] : min[0], i & 2 ? max[1] : min[1], i & 4 ? max[2] : min[2]];
    const w = [
      m[0] * p[0] + m[4] * p[1] + m[8] * p[2] + m[12],
      m[1] * p[0] + m[5] * p[1] + m[9] * p[2] + m[13],
      m[2] * p[0] + m[6] * p[1] + m[10] * p[2] + m[14],
    ];
    for (let a = 0; a < 3; a++) {
      outMin[a] = Math.min(outMin[a], w[a]);
      outMax[a] = Math.max(outMax[a], w[a]);
    }
  }
  return { min: outMin, max: outMax };
}

/** World-space AABB + tri count of every mesh node in a document. */
function partBounds(doc) {
  const parts = [];
  for (const scene of doc.getRoot().listScenes()) {
    scene.traverse((node) => {
      const mesh = node.getMesh();
      if (!mesh) return;
      const m = node.getWorldMatrix();
      let min = [Infinity, Infinity, Infinity];
      let max = [-Infinity, -Infinity, -Infinity];
      let tris = 0;
      for (const prim of mesh.listPrimitives()) {
        const pos = prim.getAttribute("POSITION");
        if (!pos) continue;
        const b = transformBounds(pos.getMin([]), pos.getMax([]), m);
        for (let a = 0; a < 3; a++) {
          min[a] = Math.min(min[a], b.min[a]);
          max[a] = Math.max(max[a], b.max[a]);
        }
        const idx = prim.getIndices();
        tris += idx ? idx.getCount() / 3 : pos.getCount() / 3;
      }
      parts.push({
        name: node.getName() || mesh.getName() || "part",
        center: min.map((v, a) => +((v + max[a]) / 2).toFixed(3)),
        size: min.map((v, a) => +(max[a] - v).toFixed(3)),
        tris: Math.round(tris),
      });
    });
  }
  return parts;
}

// --table mode: one compact row per part (for quickly reading anatomy).
if (process.argv[2] === "--table") {
  for (const file of process.argv.slice(3)) {
    const doc = await io.read(file);
    console.log(`\n== ${path.basename(path.dirname(file)).toLowerCase()} ==`);
    for (const p of partBounds(doc)) {
      console.log(
        `${p.name.padEnd(14)} c(${p.center.map((v) => v.toFixed(2)).join(",")}) s(${p.size
          .map((v) => v.toFixed(2))
          .join(",")}) tris:${p.tris}`,
      );
    }
  }
  process.exit(0);
}

// --fixtures mode: emit a TypeScript fixture module with real per-part bounds.
if (process.argv[2] === "--fixtures") {
  const entries = [];
  for (const file of process.argv.slice(3)) {
    const doc = await io.read(file);
    const id = path.basename(path.dirname(file)).toLowerCase();
    entries.push({ id, parts: partBounds(doc) });
  }
  const body = entries
    .map(
      (e) =>
        `  ${JSON.stringify(e.id)}: ${JSON.stringify(e.parts, null, 2).replace(/\n/g, "\n  ")},`,
    )
    .join("\n");
  console.log(
    `/** REAL measured part bounds of the 10 Tripo creature GLBs (world-space AABB\n` +
      ` *  per mesh node). Generated by tools/inspect-glb.mjs --fixtures — do not\n` +
      ` *  hand-edit; re-run the tool if an asset is regenerated. */\n` +
      `export interface FixturePart {\n  name: string;\n  center: [number, number, number];\n  size: [number, number, number];\n  tris: number;\n}\n\n` +
      `export const CREATURE_PART_FIXTURES: Record<string, FixturePart[]> = {\n${body}\n};\n`,
  );
  process.exit(0);
}

function meshStats(mesh) {
  let tris = 0;
  let verts = 0;
  const mats = new Set();
  for (const prim of mesh.listPrimitives()) {
    const idx = prim.getIndices();
    const pos = prim.getAttribute("POSITION");
    tris += idx ? idx.getCount() / 3 : pos ? pos.getCount() / 3 : 0;
    verts += pos ? pos.getCount() : 0;
    const m = prim.getMaterial();
    if (m) mats.add(m.getName() || "(unnamed)");
  }
  return { tris: Math.round(tris), verts, mats: [...mats] };
}

function nodeTree(node, depth, out) {
  const mesh = node.getMesh();
  const t = node.getTranslation();
  const s = node.getScale();
  const stats = mesh ? meshStats(mesh) : null;
  out.push(
    "  ".repeat(depth) +
      `- ${node.getName() || "(node)"}` +
      (mesh ? ` [mesh:${mesh.getName() || "?"} tris:${stats.tris} mats:${stats.mats.join(",")}]` : "") +
      (t.some((v) => Math.abs(v) > 1e-4) ? ` t(${t.map((v) => v.toFixed(2)).join(",")})` : "") +
      (s.some((v) => Math.abs(v - 1) > 1e-4) ? ` s(${s.map((v) => v.toFixed(2)).join(",")})` : ""),
  );
  for (const child of node.listChildren()) nodeTree(child, depth + 1, out);
}

for (const file of process.argv.slice(2)) {
  try {
    const doc = await io.read(file);
    const root = doc.getRoot();
    const report = inspect(doc);
    const lines = [];
    lines.push(`\n===== ${file} =====`);

    // Node hierarchy per scene
    for (const scene of root.listScenes()) {
      lines.push(`scene: ${scene.getName() || "(scene)"}`);
      for (const node of scene.listChildren()) nodeTree(node, 1, lines);
    }

    // Overall bounds
    const sceneRep = report.scenes.properties[0];
    if (sceneRep) {
      const min = sceneRep.bboxMin.map((v) => v.toFixed(3));
      const max = sceneRep.bboxMax.map((v) => v.toFixed(3));
      const size = sceneRep.bboxMax.map((v, i) => (v - sceneRep.bboxMin[i]).toFixed(3));
      lines.push(`bbox min(${min}) max(${max}) size(${size})`);
      lines.push(`render verts: ${sceneRep.renderVertexCount ?? "?"}`);
    }

    // Materials
    for (const m of root.listMaterials()) {
      const base = m.getBaseColorTexture();
      const mr = m.getMetallicRoughnessTexture();
      const nrm = m.getNormalTexture();
      const texInfo = (t) => (t ? `${t.getSize()?.join("x")}` : "none");
      lines.push(
        `material "${m.getName() || "(unnamed)"}" metal:${m.getMetallicFactor().toFixed(2)} rough:${m
          .getRoughnessFactor()
          .toFixed(2)} baseTex:${texInfo(base)} mrTex:${texInfo(mr)} normalTex:${texInfo(nrm)} alpha:${m.getAlphaMode()} doubleSided:${m.getDoubleSided()}`,
      );
    }

    // Animations / skins
    const anims = root.listAnimations().map((a) => a.getName() || "(unnamed)");
    lines.push(`animations: ${anims.length ? anims.join(", ") : "none"}`);
    lines.push(`skins: ${root.listSkins().length}`);
    console.log(lines.join("\n"));
  } catch (err) {
    console.log(`\n===== ${file} =====\nERROR: ${err.message}`);
  }
}
